// AUTO-GENERATED by scripts/generate-database.mjs - do not edit
// Run: node scripts/generate-database.mjs

import data0 from "@/data/Fpsgadgets_Utilities/FPS_WEAPONS.json";
import data1 from "@/data/Personal_Armor/PERSONAL_ARMOR.json";
import data2 from "@/data/Vehicle_Components/COOLERS.json";
import data3 from "@/data/Vehicle_Components/EMPS.json";
import data4 from "@/data/Vehicle_Components/FLIGHTBLADES.json";
import data5 from "@/data/Vehicle_Components/JUMPDRIVES.json";
import data6 from "@/data/Vehicle_Components/LIFESUPPORTGENERATORS.json";
import data7 from "@/data/Vehicle_Components/MININGMODIFIERS.json";
import data8 from "@/data/Vehicle_Components/POWERPLANTS.json";
import data9 from "@/data/Vehicle_Components/QUANTUMDRIVES.json";
import data10 from "@/data/Vehicle_Components/QUANTUMINTERDICTIONGENERATORS.json";
import data11 from "@/data/Vehicle_Components/RADARS.json";
import data12 from "@/data/Vehicle_Components/SALVAGEMODIFIERS.json";
import data13 from "@/data/Vehicle_Components/SELFDESTRUCTS.json";
import data14 from "@/data/Vehicle_Components/SHIELDS.json";
import data15 from "@/data/Vehicle_Components/TRACTORBEAMS.json";
import data16 from "@/data/Vehicle_Components/WEAPONDEFENSIVE.json";
import data17 from "@/data/Vehicle_Components/WEAPONMINING.json";
import data18 from "@/data/Vehicle_Weaponry/BOMBLAUNCHERS.json";
import data19 from "@/data/Vehicle_Weaponry/BOMBS.json";
import data20 from "@/data/Vehicle_Weaponry/MISSILERACKS.json";
import data21 from "@/data/Vehicle_Weaponry/MISSILES.json";
import data22 from "@/data/Vehicle_Weaponry/TURRETS.json";
import data23 from "@/data/Vehicle_Weaponry/WEAPONS.json";
import data24 from "@/data/Vehicles/SHIPS_AND_VEHICLES.json";
import data25 from "@/data/Weapon_Attachments/WEAPON_ATTACHMENTS.json";

export const categories = [
  { id: "all", label: "Everything" },
  { id: "Fpsgadgets_Utilities", label: "FPS Gadgets & Utilities" },
  { id: "Personal_Armor", label: "Personal Armor" },
  { id: "Vehicle_Components", label: "Ship Components" },
  { id: "Vehicle_Weaponry", label: "Ship Weapons" },
  { id: "Vehicles", label: "Ships & Vehicles" },
  { id: "Weapon_Attachments", label: "Weapon Attachments" }
] as const;

export const subcategories = [
  { id: "FPSWeapons", label: "FPS Weapons", category: "Fpsgadgets_Utilities" },
  { id: "PersonalArmor", label: "Personal Armor", category: "Personal_Armor" },
  { id: "Coolers", label: "Coolers", category: "Vehicle_Components" },
  { id: "ShipEMP", label: "Ship EMP", category: "Vehicle_Components" },
  { id: "FlightBlades", label: "Flight Blades", category: "Vehicle_Components" },
  { id: "JumpDrives", label: "Jump Drives", category: "Vehicle_Components" },
  { id: "LifeSupport", label: "Life Support", category: "Vehicle_Components" },
  { id: "MiningModifiers", label: "Mining Modifiers", category: "Vehicle_Components" },
  { id: "PowerPlants", label: "Power Plants", category: "Vehicle_Components" },
  { id: "QuantumDrives", label: "Quantum Drives", category: "Vehicle_Components" },
  { id: "QuantumInterdictionGenerators", label: "Quantum Interdiction", category: "Vehicle_Components" },
  { id: "Radars", label: "Radars", category: "Vehicle_Components" },
  { id: "SalvageModifiers", label: "Salvage Modifiers", category: "Vehicle_Components" },
  { id: "SelfDestructs", label: "Self Destructs", category: "Vehicle_Components" },
  { id: "Shields", label: "Shields", category: "Vehicle_Components" },
  { id: "TractorBeams", label: "Tractor Beams", category: "Vehicle_Components" },
  { id: "WeaponDefensive", label: "Weapon Defensive", category: "Vehicle_Components" },
  { id: "WeaponMining", label: "Weapon Mining", category: "Vehicle_Components" },
  { id: "BombLaunchers", label: "Bomb Launchers", category: "Vehicle_Weaponry" },
  { id: "Bombs", label: "Bombs", category: "Vehicle_Weaponry" },
  { id: "MissileRacks", label: "Missile Racks", category: "Vehicle_Weaponry" },
  { id: "Missiles", label: "Missiles", category: "Vehicle_Weaponry" },
  { id: "Turrets", label: "Turrets", category: "Vehicle_Weaponry" },
  { id: "Weapons", label: "Weapons", category: "Vehicle_Weaponry" },
  { id: "ShipsVehicles", label: "Ships & Vehicles", category: "Vehicles" },
  { id: "WeaponAttachments", label: "Weapon Attachments", category: "Weapon_Attachments" }
] as const;

export const dataEntries = [
  { category: "Fpsgadgets_Utilities", subcategory: "FPSWeapons", items: data0 },
  { category: "Personal_Armor", subcategory: "PersonalArmor", items: data1 },
  { category: "Vehicle_Components", subcategory: "Coolers", items: data2 },
  { category: "Vehicle_Components", subcategory: "ShipEMP", items: data3 },
  { category: "Vehicle_Components", subcategory: "FlightBlades", items: data4 },
  { category: "Vehicle_Components", subcategory: "JumpDrives", items: data5 },
  { category: "Vehicle_Components", subcategory: "LifeSupport", items: data6 },
  { category: "Vehicle_Components", subcategory: "MiningModifiers", items: data7 },
  { category: "Vehicle_Components", subcategory: "PowerPlants", items: data8 },
  { category: "Vehicle_Components", subcategory: "QuantumDrives", items: data9 },
  { category: "Vehicle_Components", subcategory: "QuantumInterdictionGenerators", items: data10 },
  { category: "Vehicle_Components", subcategory: "Radars", items: data11 },
  { category: "Vehicle_Components", subcategory: "SalvageModifiers", items: data12 },
  { category: "Vehicle_Components", subcategory: "SelfDestructs", items: data13 },
  { category: "Vehicle_Components", subcategory: "Shields", items: data14 },
  { category: "Vehicle_Components", subcategory: "TractorBeams", items: data15 },
  { category: "Vehicle_Components", subcategory: "WeaponDefensive", items: data16 },
  { category: "Vehicle_Components", subcategory: "WeaponMining", items: data17 },
  { category: "Vehicle_Weaponry", subcategory: "BombLaunchers", items: data18 },
  { category: "Vehicle_Weaponry", subcategory: "Bombs", items: data19 },
  { category: "Vehicle_Weaponry", subcategory: "MissileRacks", items: data20 },
  { category: "Vehicle_Weaponry", subcategory: "Missiles", items: data21 },
  { category: "Vehicle_Weaponry", subcategory: "Turrets", items: data22 },
  { category: "Vehicle_Weaponry", subcategory: "Weapons", items: data23 },
  { category: "Vehicles", subcategory: "ShipsVehicles", items: data24 },
  { category: "Weapon_Attachments", subcategory: "WeaponAttachments", items: data25 }
] as const;
