// AUTO-GENERATED by scripts/generate-database.mjs - do not edit
// Run: node scripts/generate-database.mjs

import data0 from "@/data/Fpsgadgets_Utilities/HACKINGCHIPS.json";
import data1 from "@/data/Fpsgadgets_Utilities/TOOLATTACHMENTS.json";
import data2 from "@/data/Fpsgadgets_Utilities/TOOLS.json";
import data3 from "@/data/Other/MISCELLANOUS.json";
import data4 from "@/data/Vehicle_Components/COOLERS.json";
import data5 from "@/data/Vehicle_Components/FLIGHTBLADES.json";
import data6 from "@/data/Vehicle_Components/JUMPDRIVES.json";
import data7 from "@/data/Vehicle_Components/LIFESUPPORTGENERATORS.json";
import data8 from "@/data/Vehicle_Components/POWERPLANTS.json";
import data9 from "@/data/Vehicle_Components/QUANTUMDRIVES.json";
import data10 from "@/data/Vehicle_Components/SHIELDS.json";
import data11 from "@/data/Vehicle_Weaponry/BOMBLAUNCHERS.json";
import data12 from "@/data/Vehicle_Weaponry/BOMBS.json";
import data13 from "@/data/Vehicle_Weaponry/MISSILERACKS.json";
import data14 from "@/data/Vehicle_Weaponry/MISSILES.json";
import data15 from "@/data/Vehicle_Weaponry/TURRETS.json";
import data16 from "@/data/Vehicle_Weaponry/WEAPONS.json";

export const categories = [
  { id: "all", label: "All Items" },
  { id: "Fpsgadgets_Utilities", label: "FPS Gadgets & Utilities" },
  { id: "Other", label: "Miscellaneous" },
  { id: "Vehicle_Components", label: "Ship Components" },
  { id: "Vehicle_Weaponry", label: "Ship Weapons" }
] as const;

export const subcategories = [
  { id: "HackingChips", label: "Hacking Chips", category: "Fpsgadgets_Utilities" },
  { id: "ToolAttachments", label: "Tool Attachments", category: "Fpsgadgets_Utilities" },
  { id: "Tools", label: "Tools", category: "Fpsgadgets_Utilities" },
  { id: "Miscellaneous", label: "Miscellaneous", category: "Other" },
  { id: "Coolers", label: "Coolers", category: "Vehicle_Components" },
  { id: "FlightBlades", label: "Flight Blades", category: "Vehicle_Components" },
  { id: "JumpDrives", label: "Jump Drives", category: "Vehicle_Components" },
  { id: "LifeSupport", label: "Life Support", category: "Vehicle_Components" },
  { id: "PowerPlants", label: "Power Plants", category: "Vehicle_Components" },
  { id: "QuantumDrives", label: "Quantum Drives", category: "Vehicle_Components" },
  { id: "Shields", label: "Shields", category: "Vehicle_Components" },
  { id: "BombLaunchers", label: "Bomb Launchers", category: "Vehicle_Weaponry" },
  { id: "Bombs", label: "Bombs", category: "Vehicle_Weaponry" },
  { id: "MissileRacks", label: "Missile Racks", category: "Vehicle_Weaponry" },
  { id: "Missiles", label: "Missiles", category: "Vehicle_Weaponry" },
  { id: "Turrets", label: "Turrets", category: "Vehicle_Weaponry" },
  { id: "Weapons", label: "Weapons", category: "Vehicle_Weaponry" }
] as const;

export const dataEntries = [
  { category: "Fpsgadgets_Utilities", subcategory: "HackingChips", items: data0 },
  { category: "Fpsgadgets_Utilities", subcategory: "ToolAttachments", items: data1 },
  { category: "Fpsgadgets_Utilities", subcategory: "Tools", items: data2 },
  { category: "Other", subcategory: "Miscellaneous", items: data3 },
  { category: "Vehicle_Components", subcategory: "Coolers", items: data4 },
  { category: "Vehicle_Components", subcategory: "FlightBlades", items: data5 },
  { category: "Vehicle_Components", subcategory: "JumpDrives", items: data6 },
  { category: "Vehicle_Components", subcategory: "LifeSupport", items: data7 },
  { category: "Vehicle_Components", subcategory: "PowerPlants", items: data8 },
  { category: "Vehicle_Components", subcategory: "QuantumDrives", items: data9 },
  { category: "Vehicle_Components", subcategory: "Shields", items: data10 },
  { category: "Vehicle_Weaponry", subcategory: "BombLaunchers", items: data11 },
  { category: "Vehicle_Weaponry", subcategory: "Bombs", items: data12 },
  { category: "Vehicle_Weaponry", subcategory: "MissileRacks", items: data13 },
  { category: "Vehicle_Weaponry", subcategory: "Missiles", items: data14 },
  { category: "Vehicle_Weaponry", subcategory: "Turrets", items: data15 },
  { category: "Vehicle_Weaponry", subcategory: "Weapons", items: data16 }
] as const;
